export const luxurySkincareUnderwater = {
  enabled: true,
  forceUnderwaterPreview: false,
  shallowColor: "#46c7bd",
  midDepthColor: "#08798b",
  deepColor: "#023a5f",
  fogColor: "#06586a",
  fogDensity: 0.62,
  depthGradientStrength: 1.18,
  absorptionStrength: 0.72,
  crossingBlendDistance: 0.34,
  overallOpacity: 0.92,
  horizonLightColor: "#f2d6a6",
  horizonLightStrength: 0.18,
  noiseScale: 1.65,
  noiseSpeed: 0.025,
  backdropHeight: 7.2,
  backdropWidthMultiplier: 2.65,
  volumeOpacity: 0.92,

  raysEnabled: true,
  rayColor: "#bff8ea",
  rayIntensity: 0.38,
  rayOpacity: 0.22,
  rayDensity: 22,
  rayTopRadius: 0.035,
  rayBottomRadius: 0.42,
  rayScale: 1.1,
  rayLength: 6.4,
  raySpread: 1.35,
  rayLightMargin: 0.18,
  raySpeed: 0.035,
  rayOriginX: 0.8,
  rayOriginY: 0.03,
  rayOriginZ: 0,
  rayDirectionX: -0.28,
  rayDirectionY: -1,
  rayDirectionZ: 0.16,
  rayDepthFade: 0.88,

  causticsEnabled: true,
  causticsColor: "#c8fff2",
  causticsIntensity: 0.12,
  causticsScale: 4.6,
  causticsSpeed: 0.045,
  causticsDistortion: 0.18,
  causticsDepthFade: 0.72,

  particlesEnabled: true,
  particleCount: 180,
  particleOpacity: 0.18,
  particleSize: 0.022,
  particleDriftSpeed: 0.045,
  particleDriftAmount: 0.08,
  particleDepthRange: 5.6,
  particleAreaWidth: 9,
  particleAreaHeight: 5.4,
  particleAreaDepth: 4.8,
  particleNearFade: 0.2,
  particleFarFade: 6.5,

  bubblesEnabled: true,
  bubbleCount: 30,
  bubbleSize: 0.068,
  bubbleRiseSpeed: 0.42,
  bubbleOpacity: 0.48,
  bubbleWobble: 0.11,
  bubbleColor: "#dcfff8",

  showUnderwaterBounds: false,
  showWaterSurfaceReference: false,
  hideParticles: false,
  hideRays: false,
  hideCaustics: false,
  hideBubbles: false,
  freezeUnderwaterTime: false,
};

export function makeUnderwaterPreset(overrides = {}) {
  return {
    ...luxurySkincareUnderwater,
    ...overrides,
  };
}
